### ISSUE TITLE
2 mqttk app window

### ISSUE THREAD

**Issue by electrocoder** [matesh/mqttk#10]
When you open 2 applications, the first thing to open is disconnect.

My solve 👍 
import random

self.client = Client("%s%d" % (connection_configuration["client_id"], random.randint(0, 100)),
...

**Comment by matesh** [comment]
This will not be implemented this way. 

Randomly changing the client ID can cause all sorts of problems with connections, for example: If the server is configured with ACLs that are specific to a client ID, changing the client ID specified in the configuration behind the scenes, especially without the user's knowledge, would cause totally unexpected behaviour. If in your use case this causes an issue, I recommend you to change the client ID manually before connecting the second client. 

Alternatively, I could add an option in the connection configuration (a check box) to allow MQTTk to generate a unique client ID (random UUID) just before connecting.

**Comment by electrocoder** [comment]
There are 2 computers in the office and this is how I solved the problem. It would be nice to add a random UUID option.

**Comment by matesh** [comment]
This has been added to the test branch too.
