### ISSUE TITLE
Why export_messages base64

### ISSUE THREAD

**Issue by electrocoder** [matesh/mqttk#8]
Why export messages base64 formatting.

**Comment by matesh** [comment]
Hello @electrocoder ,

This was the default behaviour of MQTT.fx, also, the JSON library has a hard time with processing binary data, so I decided to replicate this behaviour. I'm currently doing some rework on the message exporting anyway, if you have any suggestions, feel free to share. I work a lot with binary data and I usually process exported messages programmatically, so this worked for me OK.
